apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-campaign-config
  namespace: hackathon-9nett
data:
  ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=hackathondb;User=appuser;Password=app123;"
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Kubernetes"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"