apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-campaign-config
  namespace: hackathon-9nett
data:
  ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=hackathondb;User=appuser;Password=app123;"
  RABBITMQ_HOST: "rabbitmq"
  ASPNETCORE_URLS: "http://+:8080"