apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-campaign-config
  namespace: hackathon-9nett
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  MYSQL_CONNECTION: "Server=mysql;Port=3306;Database=hackathondb;User=root;Password=root;"
  RABBITMQ_HOST: "rabbitmq"