apiVersion: v1
kind: Service
metadata:
  name: identity-campaign
  namespace: hackathon-9nett
spec:
  type: ClusterIP
  selector:
    app: identity-campaign
  ports:
    - name: http
      port: 8080
      targetPort: 8080