apiVersion: v1
kind: Service
metadata:
  name: identity-campaign-service
  namespace: hackathon-9nett
spec:
  selector:
    app: identity-campaign
  ports:
    - name: http
      protocol: TCP
      port: 80
