global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'identity-campaign-api'

    metrics_path: '/metrics'

    scheme: http

    static_configs:
      - targets: ['identitycampaign.api:8080']
